version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresPass
      - POSTGRES_DB=forest_local
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 16432:5432
