version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresPass
      - POSTGRES_DB=forest_of_habits
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "17432:5432"
  forest-of-habits-api:
    depends_on:
      - db
    build: .
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/forest_of_habits
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgresPass
    profiles: [api]
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  forest_of_habits:
