server:
  port: 8082
#  servlet:
#    context-path: /api

spring:
  application.name: forest_of_habits_local
  datasource:
    url: jdbc:postgresql://localhost:17432/forest_local
    username: postgres
    password: postgresPass
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/db.changelog-master.yaml
    enabled: true

jwt:
  expiration: 60
  secret:
    key: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==

#logging:
#  level:
#    root: DEBUG