server:
  port: 8082

spring:
  application.name: forest_of_habits_local
  datasource:
    url: jdbc:postgresql://localhost:16432/forest_local
    username: postgres
    password: postgresPass
    driver-class-name: org.postgresql.Driver

jwt:
  secret:
    key: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==